name: systemd
fullname: systemd
subdomain: systemd
bg_color: '#30D475'
fg_color: '#30D475'
project_url: https://www.freedesktop.org/wiki/Software/systemd/
description: |
  "systemd is a suite of basic building blocks for a Linux system. It provides a system and service manager that runs as PID 1 and starts the rest of the system. systemd provides aggressive parallelization capabilities, uses socket and D-Bus activation for starting services, offers on-demand starting of daemons, keeps track of processes using Linux control groups, maintains mount and automount points, and implements an elaborate transactional dependency-based service control logic. systemd supports SysV and LSB init scripts and works as a replacement for sysvinit." -systemd website
git_commit_url_prefix: https://github.com/systemd/systemd/commit/

github_search_url_prefix: https://github.com/systemd/systemd/search?utf8=✓&q=
github_edit_cve_url_prefix: https://github.com/VulnerabilityHistoryProject/systemd-vulnerabilities/edit/dev/cves/
vulnerabilities_description: |
  These vulnerabilities are collected from the National Vulnerabilities Database, acknowledged by the developers.
developers_description: |
  The following is a list of developers who are involved in code that was found to be vulnerable. Specifically, developers end up here if they were the author of a commit to code that was, at some point in time, fixed for a vulnerability. Note that this is NOT a comprehensive list.

# A file name that ends with this string is considered to be source code
# The way I found these was to do this at the root of the git repo
#
# find -type f | cut -c 3- | sed 's/.*\.//' | sort | uniq > ~/systemd_exts.txt
#
# Then filtered by hand. Remove anything compressed, binary, dev-tools, etc.
source_code_extensions:
  - .h
  - .c
  - .sh
  - Makefile
  - SKELETON
  - .arch
  - .automount
  - .awk
  - .build
  - .c
  - .catalog
  - .clang-format
  - .cocci
  - .conf
  - .configure
  - .css
  - .ctags
  - .dict
  - .disabled
  - .el
  - .example
  - .expected-err
  - .expected-group
  - .expected-passwd
  - .fc
  - .gperf
  - .h
  - .hwdb